//go:build !noasm && !darwin && arm64
// AUTO-GENERATED BY GOCC -- DO NOT EDIT

package simd

import "unsafe"

//go:noescape,nosplit
func f32_cosine_distance(x unsafe.Pointer, y unsafe.Pointer, result unsafe.Pointer, size uint64)
