//go:build !noasm && amd64
// AUTO-GENERATED BY GOCC -- DO NOT EDIT

package simd

import "unsafe"

//go:noescape,nosplit
func f32_cosine_distance(x unsafe.Pointer, y unsafe.Pointer, size uint64, result unsafe.Pointer)
